### ISSUE TITLE
poseFromTQ in space3D expects quaternion, but adjustment only passes euler vectors

### ISSUE THREAD

**Issue by shoeffner** [mpomarlan/schemasim#35]
I am using this code to set up MROs:

```
    scale = (1, -1, 1)
    rotation = (90, 0, 0)
    mro = MiscellaneousRigidObject(name=node['name'],
                                    object_type=node['is_a'],
                                    mesh=node['asset'],
                                    scale_adjustment=scale,
                                    rotation_adjustment=rotation,
                                    sim_scale_adjustment=scale,
                                    sim_rotation_adjustment=rotation)
```

However, when using them to interpret a scene, schemasim/util/geometry.py:50 throws an index out of bounds, as it expects a quaternion:

```
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 139, in _run_schema_simulation
    results = sg.interpretScene(schema_scene, bsim,
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 341, in interpretScene
    enet = explicateSchemas(snet, simulator)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 259, in explicateSchemas
    if not simulator.parameterizeObject(obj, constraintSchemas, collisionManager):
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/simulator.py", line 249, in parameterizeObject
    gPDTranslation = self._densityGenerationFns["translation"](obj, densityMapConstraints["translation"], orientation)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/simulator.py", line 127, in _getTranslationPD
    z = -obj.getFloorLevel(self)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/schemas/l0_schema_templates.py", line 61, in getFloorLevel
    return sim.space().floorLevel(self.getVolume(sim))
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/schemas/l0_schema_templates.py", line 59, in getVolume
    return sim.space().transformVolume(self._getVolumeInternal(sim), t, r)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/schemas/l0_schema_templates.py", line 51, in _getVolumeInternal
    return sim.space().loadVolume(self.getMeshPath(modifier=sim.space().volumePathModifier()), adjustments=self._adjustments)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/space/space3D.py", line 50, in loadVolume
    mesh = mesh.apply_transform(poseFromTQ(translation, rotation))
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/util/geometry.py", line 52, in poseFromTQ
    w = q[3]
```

Passing a quaternion which corresponds to, e.g., a rotation (-90, 0, 0) would be (0.7071, 0, 0.7071, 0), which then results in a Div0 error.
How do I pass a rotation to the MROs/the simulation?

**Comment by mpomarlan** [comment]
Could you send me an error log of the situation where you send a quaternion?

**Comment by shoeffner** [comment]
```
    scale = (1, -1, 1)
    rotation = (0.7071, 0, 0.7071, 0)
    return MiscellaneousRigidObject(name=node['name'],
                                    object_type=node['is_a'],
                                    mesh=node['asset'],
                                    scale_adjustment=scale,
                                    rotation_adjustment=rotation,
                                    sim_scale_adjustment=scale,
                                    sim_rotation_adjustment=rotation)
```

results in:

```
ile "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/streamlit/script_runner.py", line 324, in _run_script
    exec(code, module.__dict__)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 257, in <module>
    main()
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 248, in main
    schema_simulation_result = schema_simulation_section(instructions, scene)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 158, in schema_simulation_section
    simulation_results = cache_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/streamlit/caching.py", line 591, in wrapped_func
    return get_or_create_cached_value()
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/streamlit/caching.py", line 575, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 146, in cache_simulation
    return schema_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 164, in schema_simulation
    results.append(_run_schema_simulation(schema_scene, nframes, folder))
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 139, in _run_schema_simulation
    results = sg.interpretScene(schema_scene, bsim,
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 341, in interpretScene
    enet = explicateSchemas(snet, simulator)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 259, in explicateSchemas
    if not simulator.parameterizeObject(obj, constraintSchemas, collisionManager):
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/simulator.py", line 249, in parameterizeObject
    gPDTranslation = self._densityGenerationFns["translation"](obj, densityMapConstraints["translation"], orientation)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/simulator.py", line 144, in _getTranslationPD
    print("CENTROID", center, orientation, c.getTargetSurface(self)[0], c.getMovingSurface(self)[0])
```
as well as
```
Exception ignored in: 'fcl.fcl.numpy_to_mat3d'
Traceback (most recent call last):
  File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/trimesh/collision.py", line 191, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```

In turn, only `sim_*`:

```
    scale = (1, -1, 1)
    rotation = (0.7071, 0, 0.7071, 0)
    return MiscellaneousRigidObject(name=node['name'],
                                    object_type=node['is_a'],
                                    mesh=node['asset'],
                                    sim_scale_adjustment=scale,
                                    sim_rotation_adjustment=rotation)
```
Seems to work tough.
And I can't reproduce the Div0 error I encountered before, so I guess it was somewhere on my side.

What are the two different types of adjustments supposed to be?

**Comment by shoeffner** [comment]
I guess that the ignored exception in fcl.fcl.numpy_to_mat3d is a problem though... now that I got the quaternion and scales right, the cup falls through the table:

<img width="129" alt="image" src="https://user-images.githubusercontent.com/1836815/91431815-352f8580-e861-11ea-9922-1e0a01c149fe.png">

Any ideas?

**Comment by shoeffner** [comment]
Still, here are the results when checking the data from the physicssimulation:

```
{
  "PRE": {
    "true": [
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.AxisAlignment'>",
        1
      ],
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.SurfaceContainment'>",
        1
      ],
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.AxisAlignment'>",
        1
      ]
    ],
    "false": [],
    "table_0": [
      [
        "<class 'schemasim.schemas.l10_expectation.Expectation'>",
        false,
        [
          16.370493449444677
        ]
      ]
    ]
  },
  "SIMULATION": {
    "true": [
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.AxisAlignment'>",
        1
      ],
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.SurfaceContainment'>",
        1
      ],
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.AxisAlignment'>",
        1
      ]
    ],
    "false": [],
    "table_0": [
      [
        "<class 'schemasim.schemas.l10_expectation.Expectation'>",
        false,
        [
          29.212034501694774
        ]
      ]
    ]
  },
  "POST": {
    "true": [
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.AxisAlignment'>",
        1
      ],
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.SurfaceContainment'>",
        1
      ],
      [
        "<class 'schemasim.schemas.l2_geometric_primitive_relations.AxisAlignment'>",
        1
      ]
    ],
    "false": [],
    "table_0": [
      [
        "<class 'schemasim.schemas.l10_expectation.Expectation'>",
        false,
        [
          0.10713582319487236
        ]
      ]
    ]
  }
}
```
So I guess it fails the expectations as they are all false for table_0? I guess there is something still not right in me calling the new API changes.

**Comment by mpomarlan** [comment]
Thank you, I'll have a look through these logs and recreate (and hopefully solve) the problem and get back to you.

The two kinds of adjustments are applied to the stl and dae file respectively. The "sim_adjustment" goes to the dae that will be loaded in Blender, and is useful if actual simulation will be going on.

However, both scene generation and expectation checking require some processing of meshes inside schemasim itself, which is done using the trimesh library and works on stl files. These files could be, for whatever reason, different to the daes when it comes to orientation, hence the different set of adjustment parameters.

I can be even more specific with the "for whatever reason" in fact: it could be the case that the dae has a default pose of the object (what it would look like at null translation and rotation) which is modified by a transform stored in the dae. In such cases, it is likely that the corresponding stl is the shape positioned by the non-default transform in the dae, and hence that transform needs to be cancelled, or modified in some way, that is going to be different to how the dae mesh needs to be transformed since for the dae mesh, the blender setup script will begin by deleting any exceptional transforms loaded from the dae.

**Comment by mpomarlan** [comment]
Ok, I've done some testing and while the issue is a little subtle, I think we're making progress.

The problem comes from the size of the meshes I am using in my own simulations. If you try to load your own table and on that put the cup mesh coming from example-objects, you will see the cup is enormous. This has as a consequence that some things when they sample translation distributions, or surfaces, sample in fairly big steps. So it is entirely possible that, e.g., when you load a small mesh and want to get its bottom surface, you get an empty list because all the samples miss the surface.

The "space" object that does all the geometric heavy lifting has several precision parameters, but until now these were not accessible when creating a simulator object. I've changed that now. For example,

bsim = bs.BlenderSimulator(translationSamplingResolution=0.03)

seems to work fine with the glass table and the bowlBrowth mesh (I also reduce the scale of the bowl by a factor of 5, so it looks like it would fit on the table).

Have a look, see what you find.

**Comment by shoeffner** [comment]
Scale is a good point, I never scaled my objects – now I pass on the correct scale, but need to adjust the transformations again. I am looking into it – for now I still have:

```
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_mat3d'
Traceback (most recent call last):
  File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/trimesh/collision.py", line 191, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_vec3d'
Traceback (most recent call last):
  File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/trimesh/collision.py", line 191, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```

Which seems to happen when attempting to set up the scene.

**Comment by shoeffner** [comment]
After changing the scale adjustment from `(1, 1, -1)` to `np.array((1, 1, -1), dtype=np.double)` (in an attempt to resolve the issue above), I got:

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback:

File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/streamlit/script_runner.py", line 324, in _run_script
    exec(code, module.__dict__)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 255, in <module>
    main()
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 246, in main
    schema_simulation_result = schema_simulation_section(instructions, scene)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 156, in schema_simulation_section
    simulation_results = cache_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 144, in cache_simulation
    return schema_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 170, in schema_simulation
    results.append(_run_schema_simulation(schema_scene, nframes, folder))
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 145, in _run_schema_simulation
    results = sg.interpretScene(schema_scene, bsim,
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 350, in interpretScene
    script = simulator.sceneScript(enet.schemas(), sceneFolder, blender_filename="animation.blend", log_filename="animation.log", trajectories=None, render=render, nframes=nframes)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/blender_simulator.py", line 152, in sceneScript
    if o._sim_adjustments["scale"] or o._sim_adjustments["translation"] or o._sim_adjustments
```

**Comment by shoeffner** [comment]
And finally I got my Div0 again, when using (0, 0, 0, 1) as the rotation, I get:

```
ZeroDivisionError: float division by zero
Traceback:

File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/streamlit/script_runner.py", line 324, in _run_script
    exec(code, module.__dict__)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 255, in <module>
    main()
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 246, in main
    schema_simulation_result = schema_simulation_section(instructions, scene)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 156, in schema_simulation_section
    simulation_results = cache_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 144, in cache_simulation
    return schema_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 176, in schema_simulation
    results.append(_run_schema_simulation(schema_scene, nframes, folder))
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 151, in _run_schema_simulation
    results = sg.interpretScene(schema_scene, bsim,
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 350, in interpretScene
    script = simulator.sceneScript(enet.schemas(), sceneFolder, blender_filename="animation.blend", log_filename="animation.log", trajectories=None, render=render, nframes=nframes)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/blender_simulator.py", line 158, in sceneScript
    axis, angle = quaternion2AxisAngle(o._sim_adjustments["rotation"])
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/util/geometry.py", line 11, in quaternion2AxisAngle
    axis[0] = q[0] / n
```

edit:
Maybe it was not (0, 0, 0, 1), but `(-0.00149625248741359, -0.9184290766716, -0.00243668770417571, -0.395575255155563)` instead - I had two objects in it but can't say for sure which one caused the issue.

edit2:
It must be (0, 0, 0, 1) – I set it for all objects and it failed, while setting the values above did not fail.

**Comment by mpomarlan** [comment]
The np arrays being "ambiguous" is an annoying break from python's convention of non-empty lists being "True". For now, I think an explicit check against the default None will do, and I just made a pull request to that effect.

**Comment by mpomarlan** [comment]
The division by 0 issue is an embarrassing catch -- I didn't notice yet that the quaternion2AxisAngle function doesn't work for the identity rotation. Special handling for this case has now been added however.

**Comment by mpomarlan** [comment]
I'll look into the type (double vs float) thing some more. I would prefer if the adjustments are given as lists rather than numpy arrays.

**Comment by mpomarlan** [comment]
Ok, the calls to add_object now both use np arrays of datatype double. You can try using lists for the various adjustments again.

**Comment by shoeffner** [comment]
I went with tuples because of the "annoying break from python's convention", so don't worry – it's a gotcha I fell into more often than necessary.
Will update and let you know what I get! Thanks :)

**Comment by shoeffner** [comment]
The error above still seems to appear:

> ```
>   File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/trimesh/collision.py", line 191, in add_object
>     t = fcl.Transform(transform[:3, :3], transform[:3, 3])
> ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
> ```

**Comment by shoeffner** [comment]
If I apply `(-0.7071, 0, -0.7071, 0)` (`(0, 0, 0, 1) * (0, 0.7071, 0, 0.7071)`; 90 deg rotation about y axis I hope), I get:

```
IndexError: list index out of range
Traceback:

File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/streamlit/script_runner.py", line 324, in _run_script
    exec(code, module.__dict__)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 255, in <module>
    main()
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 246, in main
    schema_simulation_result = schema_simulation_section(instructions, scene)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 156, in schema_simulation_section
    simulation_results = cache_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/pipeline.py", line 144, in cache_simulation
    return schema_simulation(instructions, scene, nframes, video_dir, mock)
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 189, in schema_simulation
    results.append(_run_schema_simulation(schema_scene, nframes, folder))
File "/Users/shoeffner/Projects/dlu/dlu/schema_simulation/__init__.py", line 164, in _run_schema_simulation
    results = sg.interpretScene(schema_scene, bsim,
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 341, in interpretScene
    enet = explicateSchemas(snet, simulator)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/scene_generator.py", line 259, in explicateSchemas
    if not simulator.parameterizeObject(obj, constraintSchemas, collisionManager):
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/simulator.py", line 245, in parameterizeObject
    gPDTranslation = self._densityGenerationFns["translation"](obj, densityMapConstraints["translation"], orientation)
File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/src/schemasim/schemasim/simulators/simulator.py", line 144, in _getTranslationPD
    print("CENTROID", center, orientation, c.getTargetSurface(self)[0], c.getMovingSurface(self)[0])
```

**Comment by mpomarlan** [comment]
That last one is a "debugging" print. It could be commented out, but the fact that it fails suggests something bad is happening upstream of it.

Can you modify it to print the length of the obtained surfaces? (e.g. len(c.getTargetSurface(self))

**Comment by mpomarlan** [comment]
About the other error (the ValueError from double vs float), two questions:

a) are you sure you git pulled the most recent master version? As far as I can tell, I convert to numpy double arrays wherever fcl is used, but if that was the latest version, could you send me the complete error message from python, with the other functions along the stack?

b) The current trimesh master version does something similar when calling fcl: it casts poses as numpy double arrays. Meanwhile, the current master of python-fcl at BerkeleyAutomation doesn't issue ValueErrors for type mismatches at all (at least, not in the Transform function). Could this be some sort of version mismatch issue?

**Comment by shoeffner** [comment]
I checked the code and I am using the most recent version. I will double
check the upstream dependencies later!

**Comment by shoeffner** [comment]
```
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_mat3d'
Traceback (most recent call last):
  File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/trimesh/collision.py", line 191, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_vec3d'
Traceback (most recent call last):
  File "/Users/shoeffner/.local/share/virtualenvs/dlu-qhuMT2yw/lib/python3.8/site-packages/trimesh/collision.py", line 191, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```
Is, in fact, the full error message I see. There is no other indication of which line calls what.

**Comment by shoeffner** [comment]
I am using trimesh 3.8.4, which seems to be the latest version (https://github.com/mikedh/trimesh/releases/tag/3.8.4). 

python-fcl had version 0.0.12, the latest seems to be 0.1.12.
However, python-fcl seems to be targeted at fcl 0.5.0, and on macOS using brew the current version 0.6.1, which removes `fcl/data_types.h`, causing a new installation to fail to compile. I now have a broken installation and try to somehow fix it...

**Comment by shoeffner** [comment]
I will close this issue as it seems to be an upstream version thing, no issues happen without FCL.
